// ============================================================================
// EDTECHRA DIGITAL CLASSROOM: ACTIONS DASHBOARD (PHASE 2B)
// Central operations hub for viewing, filtering, approving, scheduling,
// and auditing AI actions triggered from Teaching Plans.
// ============================================================================

import React, { useState, useEffect } from 'react';
import {
  Sparkles,
  Clock,
  Calendar,
  CheckCircle2,
  AlertTriangle,
  RefreshCw,
  Layers,
  ArrowRight,
  ShieldCheck
} from 'lucide-react';
import { AIAction, ActionStatus, actionExecutionService } from '@/services/actionExecutionService';
import { ActionCard } from './ActionCard';

interface AIActionsDashboardProps {
  classroomId: string;
  classroomTitle?: string;
  planId?: string;
  onNavigateToPlanner?: () => void;
}

export const AIActionsDashboard: React.FC<AIActionsDashboardProps> = ({
  classroomId,
  classroomTitle,
  planId,
  onNavigateToPlanner
}) => {
  const [actions, setActions] = useState<AIAction[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [statusFilter, setStatusFilter] = useState<'all' | ActionStatus>('all');
  const [lastRefreshed, setLastRefreshed] = useState<Date>(new Date());

  const fetchActions = async () => {
    try {
      setIsLoading(true);
      const data = await actionExecutionService.getActions(
        classroomId,
        planId,
        statusFilter === 'all' ? undefined : statusFilter
      );
      setActions(data);
      setLastRefreshed(new Date());
    } catch (err) {
      console.error('[AIActionsDashboard] Error fetching actions:', err);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchActions();
  }, [classroomId, planId, statusFilter]);

  const handleActionUpdated = (updatedAction: AIAction) => {
    setActions((prev) =>
      prev.map((a) => (a.id === updatedAction.id ? updatedAction : a))
    );
  };

  // Stats calculation
  const totalCount = actions.length;
  const pendingCount = actions.filter((a) => a.status === 'pending').length;
  const scheduledCount = actions.filter((a) => a.status === 'approved' || a.scheduled_for).length;
  const completedCount = actions.filter((a) => a.status === 'completed').length;
  const failedCount = actions.filter((a) => a.status === 'failed').length;

  const filteredActions =
    statusFilter === 'all'
      ? actions
      : actions.filter((a) => a.status === statusFilter);

  return (
    <div className="space-y-6">
      {/* Top Banner / Metrics Header */}
      <div className="bg-gradient-to-br from-[#E8F7F5] via-[#E8F7F5]/90 to-[#D4EFEC] border border-[#C9E5E2] rounded-3xl p-6 sm:p-8 shadow-xs relative overflow-hidden">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 relative z-10">
          <div className="space-y-1.5 max-w-xl">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/90 border border-[#C9E5E2] text-[#087477] text-xs font-black uppercase tracking-wider shadow-2xs">
              <ShieldCheck className="w-3.5 h-3.5 text-[#087477]" />
              <span>AI Action Execution Bus</span>
            </div>
            <h2 className="text-2xl sm:text-3xl font-black text-[#173B3F] tracking-tight">
              Classroom Automation & Action Center
            </h2>
            <p className="text-xs sm:text-sm text-[#36565A] font-medium leading-relaxed">
              Inspect, approve, and execute trusted classroom interventions generated by Teaching Intelligence. All actions are safe, idempotent, and backed by pedagogical rationale.
            </p>
          </div>

          <div className="flex items-center gap-3 self-start md:self-center flex-wrap">
            <button
              type="button"
              onClick={fetchActions}
              disabled={isLoading}
              className="px-4 py-2.5 bg-white hover:bg-[#E8F7F5] border border-[#C9E5E2] text-[#087477] rounded-xl transition-all shadow-xs flex items-center gap-2 text-xs font-bold cursor-pointer active:scale-95 disabled:opacity-50"
              title="Refresh Actions"
            >
              <RefreshCw className={`w-3.5 h-3.5 ${isLoading ? 'animate-spin' : ''}`} />
              <span>Refresh</span>
            </button>
            {onNavigateToPlanner && (
              <button
                type="button"
                onClick={onNavigateToPlanner}
                className="px-4.5 py-2.5 bg-[#087477] hover:bg-[#065e60] text-white rounded-xl shadow-sm hover:shadow-md text-xs font-black transition-all flex items-center gap-2 cursor-pointer active:scale-95"
              >
                <Sparkles className="w-4 h-4 text-[#D4EFEC]" />
                <span>Open AI Teaching Planner</span>
              </button>
            )}
          </div>
        </div>

        {/* Stats Grid */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3.5 mt-6 relative z-10">
          <div className="bg-white border border-[#C9E5E2] rounded-2xl p-4 shadow-xs">
            <div className="flex items-center gap-2 text-xs font-bold text-[#36565A] uppercase tracking-wider">
              <div className="w-6 h-6 rounded-lg bg-[#E8F7F5] text-[#159A9C] flex items-center justify-center">
                <Layers className="w-3.5 h-3.5" />
              </div>
              <span>Total Actions</span>
            </div>
            <div className="text-3xl font-black text-[#173B3F] mt-2">
              {totalCount}
            </div>
          </div>

          <div className="bg-white border border-[#C9E5E2] rounded-2xl p-4 shadow-xs">
            <div className="flex items-center gap-2 text-xs font-bold text-[#D99500] uppercase tracking-wider">
              <div className="w-6 h-6 rounded-lg bg-amber-50 text-[#D99500] border border-amber-200/60 flex items-center justify-center">
                <Clock className="w-3.5 h-3.5" />
              </div>
              <span>Pending Approval</span>
            </div>
            <div className="text-3xl font-black text-[#D99500] mt-2">
              {pendingCount}
            </div>
          </div>

          <div className="bg-white border border-[#C9E5E2] rounded-2xl p-4 shadow-xs">
            <div className="flex items-center gap-2 text-xs font-bold text-[#087477] uppercase tracking-wider">
              <div className="w-6 h-6 rounded-lg bg-[#E8F7F5] text-[#087477] border border-[#C9E5E2] flex items-center justify-center">
                <Calendar className="w-3.5 h-3.5" />
              </div>
              <span>Approved / Scheduled</span>
            </div>
            <div className="text-3xl font-black text-[#087477] mt-2">
              {scheduledCount}
            </div>
          </div>

          <div className="bg-white border border-[#C9E5E2] rounded-2xl p-4 shadow-xs">
            <div className="flex items-center gap-2 text-xs font-bold text-[#159A75] uppercase tracking-wider">
              <div className="w-6 h-6 rounded-lg bg-emerald-50 text-[#159A75] border border-emerald-200/60 flex items-center justify-center">
                <CheckCircle2 className="w-3.5 h-3.5" />
              </div>
              <span>Completed</span>
            </div>
            <div className="text-3xl font-black text-[#159A75] mt-2">
              {completedCount}
            </div>
          </div>
        </div>
      </div>

      {/* Filter Tabs */}
      <div className="flex items-center justify-between border-b border-[#C9E5E2] pb-3 gap-3 flex-wrap">
        <div className="flex items-center gap-2 overflow-x-auto py-1">
          <button
            type="button"
            onClick={() => setStatusFilter('all')}
            className={`px-3.5 py-2 rounded-xl text-xs font-bold transition-all cursor-pointer select-none flex items-center gap-1.5 ${
              statusFilter === 'all'
                ? 'bg-[#087477] text-white shadow-xs'
                : 'bg-white text-[#36565A] hover:bg-[#E8F7F5] hover:text-[#173B3F] border border-[#C9E5E2]'
            }`}
          >
            <span>All Actions</span>
            <span className={`px-1.5 py-0.2 rounded-md text-[11px] font-black ${
              statusFilter === 'all' ? 'bg-white/20 text-white' : 'bg-[#E8F7F5] text-[#087477]'
            }`}>
              {totalCount}
            </span>
          </button>
          <button
            type="button"
            onClick={() => setStatusFilter('pending')}
            className={`px-3.5 py-2 rounded-xl text-xs font-bold transition-all flex items-center gap-1.5 cursor-pointer select-none ${
              statusFilter === 'pending'
                ? 'bg-[#D99500] text-white shadow-xs'
                : 'bg-white text-[#36565A] hover:bg-amber-50/60 hover:text-amber-900 border border-[#C9E5E2]'
            }`}
          >
            <Clock className="w-3.5 h-3.5" />
            <span>Pending Approval</span>
            <span className={`px-1.5 py-0.2 rounded-md text-[11px] font-black ${
              statusFilter === 'pending' ? 'bg-white/25 text-white' : 'bg-amber-50 text-[#D99500] border border-amber-200'
            }`}>
              {pendingCount}
            </span>
          </button>
          <button
            type="button"
            onClick={() => setStatusFilter('approved')}
            className={`px-3.5 py-2 rounded-xl text-xs font-bold transition-all flex items-center gap-1.5 cursor-pointer select-none ${
              statusFilter === 'approved'
                ? 'bg-[#159A9C] text-white shadow-xs'
                : 'bg-white text-[#36565A] hover:bg-[#E8F7F5] hover:text-[#087477] border border-[#C9E5E2]'
            }`}
          >
            <Calendar className="w-3.5 h-3.5" />
            <span>Approved</span>
            <span className={`px-1.5 py-0.2 rounded-md text-[11px] font-black ${
              statusFilter === 'approved' ? 'bg-white/25 text-white' : 'bg-[#E8F7F5] text-[#159A9C] border border-[#C9E5E2]'
            }`}>
              {scheduledCount}
            </span>
          </button>
          <button
            type="button"
            onClick={() => setStatusFilter('completed')}
            className={`px-3.5 py-2 rounded-xl text-xs font-bold transition-all flex items-center gap-1.5 cursor-pointer select-none ${
              statusFilter === 'completed'
                ? 'bg-[#159A75] text-white shadow-xs'
                : 'bg-white text-[#36565A] hover:bg-emerald-50 hover:text-emerald-900 border border-[#C9E5E2]'
            }`}
          >
            <CheckCircle2 className="w-3.5 h-3.5" />
            <span>Completed</span>
            <span className={`px-1.5 py-0.2 rounded-md text-[11px] font-black ${
              statusFilter === 'completed' ? 'bg-white/25 text-white' : 'bg-emerald-50 text-[#159A75] border border-emerald-200'
            }`}>
              {completedCount}
            </span>
          </button>
          {failedCount > 0 && (
            <button
              type="button"
              onClick={() => setStatusFilter('failed')}
              className={`px-3.5 py-2 rounded-xl text-xs font-bold transition-all flex items-center gap-1.5 cursor-pointer select-none ${
                statusFilter === 'failed'
                  ? 'bg-[#C94B4B] text-white shadow-xs'
                  : 'bg-white text-[#C94B4B] hover:bg-rose-50 hover:text-rose-900 border border-rose-200'
              }`}
            >
              <AlertTriangle className="w-3.5 h-3.5" />
              <span>Failed</span>
              <span className="px-1.5 py-0.2 rounded-md text-[11px] font-black bg-white/25 text-white">
                {failedCount}
              </span>
            </button>
          )}
        </div>

        <div className="text-xs font-bold text-[#36565A] hidden sm:flex items-center gap-1.5">
          <span className="w-2 h-2 rounded-full bg-[#159A75] inline-block animate-pulse" />
          <span>Synced: {lastRefreshed.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span>
        </div>
      </div>

      {/* Actions Grid */}
      {isLoading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {[1, 2, 3, 4].map((n) => (
            <div
              key={n}
              className="h-44 bg-white border border-[#C9E5E2] rounded-2xl animate-pulse"
            />
          ))}
        </div>
      ) : filteredActions.length > 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {filteredActions.map((action) => (
            <ActionCard
              key={action.id}
              action={action}
              classroomId={classroomId}
              classroomTitle={classroomTitle}
              onActionUpdated={handleActionUpdated}
            />
          ))}
        </div>
      ) : (
        /* Empty State — active, valid, non-disabled appearance */
        <div className="text-center py-16 px-6 bg-white border border-[#C9E5E2] rounded-3xl shadow-xs">
          <div className="w-14 h-14 rounded-2xl bg-[#E8F7F5] border border-[#C9E5E2] text-[#087477] flex items-center justify-center mx-auto mb-4 shadow-2xs">
            <Sparkles className="w-7 h-7 text-[#087477]" />
          </div>
          <h3 className="text-lg font-black text-[#173B3F]">
            No Actions in this View
          </h3>
          <p className="text-xs sm:text-sm text-[#36565A] font-medium max-w-md mx-auto mt-1.5 mb-6 leading-relaxed">
            {statusFilter === 'all'
              ? 'No classroom actions are pending right now. Open an approved AI Teaching Plan to convert pedagogical recommendations into executable actions.'
              : `There are currently no actions with status "${statusFilter}". Check other status tabs or open the AI Teaching Planner.`}
          </p>
          {onNavigateToPlanner && (
            <button
              type="button"
              onClick={onNavigateToPlanner}
              className="inline-flex items-center gap-2 px-5 py-3 bg-[#087477] hover:bg-[#065e60] text-white rounded-xl text-xs font-black shadow-sm hover:shadow-md transition-all cursor-pointer active:scale-95"
            >
              <span>Go to AI Teaching Planner</span>
              <ArrowRight className="w-4 h-4" />
            </button>
          )}
        </div>
      )}
    </div>
  );
};
