// ============================================================================
// EDTECHRA DIGITAL CLASSROOM: ACTIONS DASHBOARD (PHASE 2B)
// Central operations hub for viewing, filtering, approving, scheduling,
// and auditing AI actions triggered from Teaching Plans.
// ============================================================================

import React, { useState, useEffect } from 'react';
import {
  Sparkles,
  Clock,
  Calendar,
  CheckCircle2,
  AlertTriangle,
  RefreshCw,
  Layers,
  ArrowRight,
  ShieldCheck
} from 'lucide-react';
import { AIAction, ActionStatus, actionExecutionService } from '@/services/actionExecutionService';
import { ActionCard } from './ActionCard';

interface AIActionsDashboardProps {
  classroomId: string;
  classroomTitle?: string;
  planId?: string;
  onNavigateToPlanner?: () => void;
}

export const AIActionsDashboard: React.FC<AIActionsDashboardProps> = ({
  classroomId,
  classroomTitle,
  planId,
  onNavigateToPlanner
}) => {
  const [actions, setActions] = useState<AIAction[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [statusFilter, setStatusFilter] = useState<'all' | ActionStatus>('all');
  const [lastRefreshed, setLastRefreshed] = useState<Date>(new Date());

  const fetchActions = async () => {
    try {
      setIsLoading(true);
      const data = await actionExecutionService.getActions(
        classroomId,
        planId,
        statusFilter === 'all' ? undefined : statusFilter
      );
      setActions(data);
      setLastRefreshed(new Date());
    } catch (err) {
      console.error('[AIActionsDashboard] Error fetching actions:', err);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchActions();
  }, [classroomId, planId, statusFilter]);

  const handleActionUpdated = (updatedAction: AIAction) => {
    setActions((prev) =>
      prev.map((a) => (a.id === updatedAction.id ? updatedAction : a))
    );
  };

  // Stats calculation
  const totalCount = actions.length;
  const pendingCount = actions.filter((a) => a.status === 'pending').length;
  const scheduledCount = actions.filter((a) => a.status === 'approved' || a.scheduled_for).length;
  const completedCount = actions.filter((a) => a.status === 'completed').length;
  const failedCount = actions.filter((a) => a.status === 'failed').length;

  const filteredActions =
    statusFilter === 'all'
      ? actions
      : actions.filter((a) => a.status === statusFilter);

  return (
    <div className="space-y-6">
      {/* Top Banner / Metrics Header */}
      <div className="bg-gradient-to-br from-indigo-900/10 via-slate-900/5 to-blue-900/10 dark:from-indigo-950/40 dark:via-slate-900/30 dark:to-blue-950/40 border border-indigo-100 dark:border-indigo-900/40 rounded-2xl p-6 backdrop-blur-sm">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 text-xs font-bold text-indigo-600 dark:text-indigo-400 uppercase tracking-wider">
              <ShieldCheck className="w-4 h-4" />
              AI Action Execution Bus
            </div>
            <h2 className="text-xl font-black text-slate-900 dark:text-white mt-1">
              Classroom Automation & Action Center
            </h2>
            <p className="text-xs text-slate-600 dark:text-slate-400 mt-1 max-w-xl">
              Inspect, approve, and execute trusted classroom interventions generated by Teaching Intelligence. All actions are safe, idempotent, and backed by pedagogical rationale.
            </p>
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={fetchActions}
              disabled={isLoading}
              className="p-2.5 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:bg-slate-50 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-200 rounded-xl transition-all shadow-sm flex items-center gap-1.5 text-xs font-semibold"
              title="Refresh Actions"
            >
              <RefreshCw className={`w-4 h-4 ${isLoading ? 'animate-spin' : ''}`} />
              <span>Refresh</span>
            </button>
            {onNavigateToPlanner && (
              <button
                onClick={onNavigateToPlanner}
                className="px-4 py-2.5 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl shadow-md shadow-indigo-500/20 text-xs font-bold transition-all flex items-center gap-1.5"
              >
                <Sparkles className="w-4 h-4" />
                Open AI Teaching Planner
              </button>
            )}
          </div>
        </div>

        {/* Stats Grid */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-6">
          <div className="bg-white/80 dark:bg-slate-800/80 border border-slate-200/80 dark:border-slate-700/80 rounded-xl p-3.5 shadow-sm">
            <div className="flex items-center gap-2 text-xs font-semibold text-slate-500 dark:text-slate-400">
              <Layers className="w-4 h-4 text-slate-500" />
              Total Actions
            </div>
            <div className="text-2xl font-black text-slate-900 dark:text-white mt-1">
              {totalCount}
            </div>
          </div>

          <div className="bg-white/80 dark:bg-slate-800/80 border border-amber-200/80 dark:border-amber-900/40 rounded-xl p-3.5 shadow-sm">
            <div className="flex items-center gap-2 text-xs font-semibold text-amber-600 dark:text-amber-400">
              <Clock className="w-4 h-4 text-amber-500" />
              Pending Approval
            </div>
            <div className="text-2xl font-black text-amber-600 dark:text-amber-400 mt-1">
              {pendingCount}
            </div>
          </div>

          <div className="bg-white/80 dark:bg-slate-800/80 border border-blue-200/80 dark:border-blue-900/40 rounded-xl p-3.5 shadow-sm">
            <div className="flex items-center gap-2 text-xs font-semibold text-blue-600 dark:text-blue-400">
              <Calendar className="w-4 h-4 text-blue-500" />
              Scheduled / Approved
            </div>
            <div className="text-2xl font-black text-blue-600 dark:text-blue-400 mt-1">
              {scheduledCount}
            </div>
          </div>

          <div className="bg-white/80 dark:bg-slate-800/80 border border-emerald-200/80 dark:border-emerald-900/40 rounded-xl p-3.5 shadow-sm">
            <div className="flex items-center gap-2 text-xs font-semibold text-emerald-600 dark:text-emerald-400">
              <CheckCircle2 className="w-4 h-4 text-emerald-500" />
              Completed
            </div>
            <div className="text-2xl font-black text-emerald-600 dark:text-emerald-400 mt-1">
              {completedCount}
            </div>
          </div>
        </div>
      </div>

      {/* Filter Tabs */}
      <div className="flex items-center justify-between border-b border-slate-200 dark:border-slate-800 pb-3">
        <div className="flex items-center gap-1.5 overflow-x-auto py-1">
          <button
            onClick={() => setStatusFilter('all')}
            className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${
              statusFilter === 'all'
                ? 'bg-slate-900 text-white dark:bg-white dark:text-slate-900 shadow-sm'
                : 'text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800'
            }`}
          >
            All Actions ({totalCount})
          </button>
          <button
            onClick={() => setStatusFilter('pending')}
            className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all flex items-center gap-1.5 ${
              statusFilter === 'pending'
                ? 'bg-amber-600 text-white shadow-sm'
                : 'text-amber-700 dark:text-amber-400 hover:bg-amber-50 dark:hover:bg-amber-950/40'
            }`}
          >
            <Clock className="w-3 h-3" />
            Pending Approval ({pendingCount})
          </button>
          <button
            onClick={() => setStatusFilter('approved')}
            className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all flex items-center gap-1.5 ${
              statusFilter === 'approved'
                ? 'bg-blue-600 text-white shadow-sm'
                : 'text-blue-700 dark:text-blue-400 hover:bg-blue-50 dark:hover:bg-blue-950/40'
            }`}
          >
            <Calendar className="w-3 h-3" />
            Approved ({scheduledCount})
          </button>
          <button
            onClick={() => setStatusFilter('completed')}
            className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all flex items-center gap-1.5 ${
              statusFilter === 'completed'
                ? 'bg-emerald-600 text-white shadow-sm'
                : 'text-emerald-700 dark:text-emerald-400 hover:bg-emerald-50 dark:hover:bg-emerald-950/40'
            }`}
          >
            <CheckCircle2 className="w-3 h-3" />
            Completed ({completedCount})
          </button>
          {failedCount > 0 && (
            <button
              onClick={() => setStatusFilter('failed')}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all flex items-center gap-1.5 ${
                statusFilter === 'failed'
                  ? 'bg-rose-600 text-white shadow-sm'
                  : 'text-rose-700 dark:text-rose-400 hover:bg-rose-50 dark:hover:bg-rose-950/40'
              }`}
            >
              <AlertTriangle className="w-3 h-3" />
              Failed ({failedCount})
            </button>
          )}
        </div>

        <div className="text-[11px] text-slate-400 hidden sm:block">
          Auto-updated: {lastRefreshed.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
        </div>
      </div>

      {/* Actions Grid */}
      {isLoading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {[1, 2, 3, 4].map((n) => (
            <div
              key={n}
              className="h-44 bg-slate-100 dark:bg-slate-800/40 border border-slate-200 dark:border-slate-800 rounded-2xl animate-pulse"
            />
          ))}
        </div>
      ) : filteredActions.length > 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {filteredActions.map((action) => (
            <ActionCard
              key={action.id}
              action={action}
              classroomId={classroomId}
              classroomTitle={classroomTitle}
              onActionUpdated={handleActionUpdated}
            />
          ))}
        </div>
      ) : (
        <div className="text-center py-16 px-4 bg-slate-50 dark:bg-slate-900/40 border border-dashed border-slate-200 dark:border-slate-800 rounded-2xl">
          <div className="w-12 h-12 rounded-2xl bg-indigo-50 dark:bg-indigo-950/60 border border-indigo-200 dark:border-indigo-900/60 flex items-center justify-center mx-auto mb-3">
            <Sparkles className="w-6 h-6 text-indigo-500" />
          </div>
          <h3 className="text-base font-bold text-slate-900 dark:text-white">
            No Actions in this View
          </h3>
          <p className="text-xs text-slate-500 dark:text-slate-400 max-w-sm mx-auto mt-1 mb-4">
            {statusFilter === 'all'
              ? 'No classroom actions have been generated yet. Open an approved AI Teaching Plan to convert recommendations into executable actions.'
              : `There are currently no actions with status "${statusFilter}".`}
          </p>
          {onNavigateToPlanner && (
            <button
              onClick={onNavigateToPlanner}
              className="inline-flex items-center gap-1.5 px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl text-xs font-bold shadow-md transition-all"
            >
              <span>Go to AI Teaching Planner</span>
              <ArrowRight className="w-3.5 h-3.5" />
            </button>
          )}
        </div>
      )}
    </div>
  );
};
