// ============================================================================
// EDTECHRA AI OUTPUT VALIDATOR
// Server-Side Pedagogical Quality Guardrails for AI-Generated Content
// ============================================================================

const FORBIDDEN_LAZY_CHOICES = [
  'all of the above',
  'none of the above',
  'all of these',
  'none of these',
  'both a and b',
  'both b and c',
  'all choices are correct',
  'none are correct'
];

/**
 * Validates multiple-choice and short-answer questions generated by AI.
 *
 * @param {Array<object>} questions - Array of questions to validate
 * @param {object} options
 * @param {number} [options.expectedCount] - If set, enforces exact question count
 * @param {boolean} [options.enforceFourChoices=true] - If true, enforces exactly 4 choices
 * @param {boolean} [options.enforceConciseOptions=false] - If true, enforces 1-3 words per choice
 * @returns {{ isValid: boolean, errors: string[], sanitizedQuestions: Array<object> }}
 */
export function validateAssessmentQuestions(questions, options = {}) {
  const errors = [];
  const {
    expectedCount,
    enforceFourChoices = true,
    enforceConciseOptions = false
  } = options;

  if (!Array.isArray(questions) || questions.length === 0) {
    return {
      isValid: false,
      errors: ['Questions payload must be a non-empty array.'],
      sanitizedQuestions: []
    };
  }

  if (expectedCount && questions.length !== expectedCount) {
    errors.push(`Expected exactly ${expectedCount} questions, but received ${questions.length}.`);
  }

  const sanitized = [];

  for (let i = 0; i < questions.length; i++) {
    const q = questions[i];
    const qNum = i + 1;

    // 1. Question Title/Prompt
    const title = (q.title || q.question_text || q.question || '').trim();
    if (!title || title.length < 5) {
      errors.push(`Question #${qNum}: Missing or insufficiently descriptive prompt text.`);
    }

    const type = q.type || (Array.isArray(q.options) && q.options.length > 0 ? 'multiple_choice' : 'short_answer');

    if (type === 'multiple_choice') {
      const rawOptions = Array.isArray(q.options) ? q.options : [];

      // 2. Choice count
      if (enforceFourChoices && rawOptions.length !== 4) {
        errors.push(`Question #${qNum}: Expected exactly 4 options, found ${rawOptions.length}.`);
      } else if (rawOptions.length < 2) {
        errors.push(`Question #${qNum}: Multiple choice question must have at least 2 options.`);
      }

      // 3. Choice quality checks
      const cleanOptions = [];
      const seenOptions = new Set();

      for (let optIdx = 0; optIdx < rawOptions.length; optIdx++) {
        const rawOpt = String(rawOptions[optIdx] ?? '').trim();

        if (!rawOpt) {
          errors.push(`Question #${qNum}, Option #${optIdx + 1}: Empty choice text is not permitted.`);
          continue;
        }

        const normLower = rawOpt.toLowerCase().replace(/[.,!?;:]/g, '').trim();

        // Check lazy choice
        for (const forbidden of FORBIDDEN_LAZY_CHOICES) {
          if (normLower === forbidden) {
            errors.push(`Question #${qNum}: Lazy choice "${rawOpt}" is strictly forbidden in standardized educational assessments.`);
          }
        }

        // Check duplicate choices
        if (seenOptions.has(normLower)) {
          errors.push(`Question #${qNum}: Duplicate option detected ("${rawOpt}"). All answer choices must be distinct.`);
        }
        seenOptions.add(normLower);

        // Check concise options if required (e.g. Live Quiz)
        if (enforceConciseOptions) {
          const wordCount = rawOpt.split(/\s+/).length;
          if (wordCount > 4) {
            errors.push(`Question #${qNum}: Option "${rawOpt}" exceeds concise limit (found ${wordCount} words, maximum 3-4 allowed).`);
          }
        }

        cleanOptions.push(rawOpt);
      }

      // 4. Correct Answer Index Integrity
      let correctIdx = q.correct_index ?? q.correct_answer ?? 0;

      // If correct answer was passed as string matching option
      if (typeof correctIdx === 'string') {
        const found = cleanOptions.findIndex(o => o.trim().toLowerCase() === correctIdx.trim().toLowerCase());
        if (found !== -1) {
          correctIdx = found;
        } else {
          errors.push(`Question #${qNum}: Correct answer string "${correctIdx}" does not match any of the provided choices.`);
          correctIdx = 0;
        }
      }

      if (typeof correctIdx !== 'number' || correctIdx < 0 || correctIdx >= cleanOptions.length) {
        errors.push(`Question #${qNum}: Correct answer index (${correctIdx}) is out of bounds [0..${cleanOptions.length - 1}].`);
        correctIdx = 0;
      }

      sanitized.push({
        id: q.id || `q_${qNum}`,
        question_index: i,
        title,
        question_text: title,
        type: 'multiple_choice',
        options: cleanOptions,
        correct_index: correctIdx,
        correct_answer: correctIdx,
        marks: Number(q.marks) || 2,
        duration_minutes: Number(q.duration_minutes) || 2,
        duration_sec: Number(q.duration_sec) || 20,
        explanation: (q.explanation || '').trim() || 'Correct pedagogical answer.'
      });
    } else {
      // Short answer question
      const answer = String(q.correct_answer || q.answer || '').trim();
      sanitized.push({
        id: q.id || `q_${qNum}`,
        question_index: i,
        title,
        question_text: title,
        type: 'short_answer',
        options: [],
        correct_answer: answer,
        marks: Number(q.marks) || 2,
        duration_minutes: Number(q.duration_minutes) || 3,
        explanation: (q.explanation || '').trim() || 'Correct model answer.'
      });
    }
  }

  return {
    isValid: errors.length === 0,
    errors,
    sanitizedQuestions: sanitized
  };
}

/**
 * Shuffles question options while guaranteeing the correct_index tracks the correct choice.
 *
 * @param {object} question - Single question object
 * @returns {object} Question with shuffled options and updated correct_index
 */
export function shuffleOptionsWithAnswerTracking(questionOrOptions, maybeCorrect) {
  let question = null;
  if (Array.isArray(questionOrOptions)) {
    question = {
      options: questionOrOptions,
      correct_answer: maybeCorrect
    };
  } else {
    question = questionOrOptions || {};
  }

  if (!question || !Array.isArray(question.options) || question.options.length < 2) {
    return question;
  }

  let correctText = '';
  if (typeof question.correct_index === 'number' && question.options[question.correct_index] !== undefined) {
    correctText = question.options[question.correct_index];
  } else if (typeof question.correct_answer === 'string') {
    correctText = question.correct_answer;
  } else if (typeof question.correct_answer === 'number' && question.options[question.correct_answer] !== undefined) {
    correctText = question.options[question.correct_answer];
  }

  const items = question.options.map((opt, idx) => ({
    opt,
    isCorrect: correctText ? (opt.trim().toLowerCase() === correctText.trim().toLowerCase()) : (idx === question.correct_index)
  }));

  // Fisher-Yates shuffle
  for (let i = items.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [items[i], items[j]] = [items[j], items[i]];
  }

  const newOptions = items.map(it => it.opt);
  const newCorrectIndex = items.findIndex(it => it.isCorrect);

  return {
    ...question,
    options: newOptions,
    correct_index: newCorrectIndex !== -1 ? newCorrectIndex : 0,
    correct_answer: correctText || (newCorrectIndex !== -1 ? newCorrectIndex : 0)
  };
}

/**
 * Validates structured AI Teaching Plan output.
 *
 * @param {object} plan - AI Teaching Plan
 * @returns {{ isValid: boolean, errors: string[] }}
 */
export function validateTeachingPlan(plan) {
  const errors = [];
  if (!plan || typeof plan !== 'object') {
    return { isValid: false, errors: ['Teaching plan must be a non-empty object.'] };
  }

  if (!plan.title || plan.title.length < 3) errors.push('Missing plan title.');
  if (!plan.topic || plan.topic.length < 2) errors.push('Missing plan topic.');

  const days = plan.daily_plan || plan.daily_plans || [];
  if (!Array.isArray(days) || days.length === 0) {
    errors.push('Daily plan must contain at least one day.');
  } else {
    for (let i = 0; i < days.length; i++) {
      const d = days[i];
      if (!d.title) errors.push(`Day ${i + 1} missing title.`);
      if (!Array.isArray(d.activities) || d.activities.length === 0) {
        errors.push(`Day ${i + 1} missing lesson activities.`);
      }
    }
  }

  return {
    isValid: errors.length === 0,
    errors
  };
}
